### ISSUE TITLE
waitとjobの終わりを監視する処理でwaitpidの取り合いになる

### ISSUE THREAD

**Issue by ryuichiueda** [shellgei/rusty_bash#64]
job構造体でしっかり状態を管理しないといけない。

```
$ RUST_BACKTRACE=1 cargo run 
    Finished dev [unoptimized + debuginfo] target(s) in 0.04s
     Running `/home/ueda/GIT/rusty_bash/target/debug/rusty_bash`
ueda@x1:~/GIT/rusty_bash/test$ sleep 1 & wait
[1] 30141
thread 'main' panicked at 'Faild to wait child process.: ECHILD', src/core.rs:236:56
stack backtrace:
   0: rust_begin_unwind
             at /build/rustc-ZOqcvC/rustc-1.61.0+dfsg1/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /build/rustc-ZOqcvC/rustc-1.61.0+dfsg1/library/core/src/panicking.rs:143:14
   2: core::result::unwrap_failed
             at /build/rustc-ZOqcvC/rustc-1.61.0+dfsg1/library/core/src/result.rs:1785:5
   3: core::result::Result<T,E>::expect
             at /build/rustc-ZOqcvC/rustc-1.61.0+dfsg1/library/core/src/result.rs:1035:23
   4: rusty_bash::core::ShellCore::check_process
             at /home/ueda/GIT/rusty_bash/src/core.rs:236:15
   5: rusty_bash::core::job::Job::check_of_finish
             at /home/ueda/GIT/rusty_bash/src/core/job.rs:46:18
   6: rusty_bash::core::ShellCore::check_jobs
             at /home/ueda/GIT/rusty_bash/src/core.rs:245:17
   7: rusty_bash::main_loop
             at /home/ueda/GIT/rusty_bash/src/main.rs:156:9
   8: rusty_bash::main
             at /home/ueda/GIT/rusty_bash/src/main.rs:134:5
   9: core::ops::function::FnOnce::call_once
             at /build/rustc-ZOqcvC/rustc-1.61.0+dfsg1/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by ryuichiueda** [comment]
あるいはwait単体でコケてるかも

**Comment by ryuichiueda** [comment]
ちょっとコードが汚くなったけど解決
